### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'int com.google.android.gms.location.LocationRequest.b' on a null object reference

### ISSUE THREAD

**Issue by gustavomc** [jbj88817/getLastLocationUsingGPS-android#1]
08-08 21:01:06.827  13794-13794/com.bojie.locationex E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.bojie.locationex, PID: 13794
    java.lang.NullPointerException: Attempt to read from field 'int com.google.android.gms.location.LocationRequest.b' on a null object reference
            at android.os.Parcel.readException(Parcel.java:1552)
            at android.os.Parcel.readException(Parcel.java:1499)
            at com.google.android.gms.location.internal.zzg$zza$zza.zza(Unknown Source)
            at com.google.android.gms.location.internal.zzi.zza(Unknown Source)
            at com.google.android.gms.location.internal.zzj.zza(Unknown Source)
            at com.google.android.gms.location.internal.zzd$1.zza(Unknown Source)
            at com.google.android.gms.location.internal.zzd$1.zza(Unknown Source)
            at com.google.android.gms.common.api.zza$zza.zzb(Unknown Source)
            at com.google.android.gms.common.api.zzd.zza(Unknown Source)
            at com.google.android.gms.common.api.zzd.zzb(Unknown Source)
            at com.google.android.gms.common.api.zzg.zzb(Unknown Source)
            at com.google.android.gms.location.internal.zzd.requestLocationUpdates(Unknown Source)
            at com.bojie.locationex.MapsActivity.onConnected(MapsActivity.java:163)
            at com.google.android.gms.common.internal.zzj.zzg(Unknown Source)
            at com.google.android.gms.common.api.zze.zzmH(Unknown Source)
            at com.google.android.gms.common.api.zze.onConnected(Unknown Source)
            at com.google.android.gms.common.api.zzg$2.onConnected(Unknown Source)
            at com.google.android.gms.common.internal.zzi$zzg.zznO(Unknown Source)
            at com.google.android.gms.common.internal.zzi$zza.zzc(Unknown Source)
            at com.google.android.gms.common.internal.zzi$zza.zzr(Unknown Source)
            at com.google.android.gms.common.internal.zzi$zzc.zznQ(Unknown Source)
            at com.google.android.gms.common.internal.zzi$zzb.handleMessage(Unknown Source)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by jbj88817** [comment]
Thanks for reporting this issue. When did this happened? On which device and what what build number of your device? Thanks.

**Comment by jbj88817** [comment]
I have changed some. Please try again

**Comment by gustavomc** [comment]
yeah thanks it worked, my build number is LMY48I

**Comment by jbj88817** [comment]
Glad to hear that, enjoy!

**Comment by kapeel45** [comment]
Hi everyone i too got the same error for my OnePlusOne device can i get the solution
